DROP TABLE IF EXISTS PACKS;
DROP TABLE IF EXISTS PARAMETERS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS EQUIPMENT_TYPES;
DROP TABLE IF EXISTS POSITIONS;


CREATE TABLE POSITIONS (
    CODE VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    UNIQUE (CODE)
);

CREATE TABLE USERS (
    CODE            VARCHAR(20) NOT NULL PRIMARY KEY,
    FULL_NAME       VARCHAR(100) NOT NULL,
    POSITION_CODE   VARCHAR(20) NOT NULL,
    UNIQUE (CODE),
    FOREIGN KEY (POSITION_CODE) REFERENCES POSITIONS (CODE)
);

CREATE TABLE EQUIPMENT_TYPES (
    CODE        VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200),
    UNIQUE (CODE)
);

CREATE TABLE PARAMETERS (
    CODE                VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME                VARCHAR(100) NOT NULL,
    VALUE               VARCHAR(100),
    UNIT                VARCHAR(20),
    EQUIPMENT_TYPE_CODE VARCHAR(20) NOT NULL,
    UNIQUE (CODE),
    FOREIGN KEY (EQUIPMENT_TYPE_CODE) REFERENCES EQUIPMENT_TYPES (CODE)
);

CREATE TABLE PACKS (
    CODE            VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME            VARCHAR(100) NOT NULL,
    CREATED_DATE     DATE,
    USER_CODE       VARCHAR(20) NOT NULL,
    PARAMETER_CODE  VARCHAR(20) NOT NULL,
    UNIQUE (CODE),
    FOREIGN KEY (USER_CODE) REFERENCES USERS (CODE),
    FOREIGN KEY (PARAMETER_CODE) REFERENCES PARAMETERS (CODE)
);


INSERT INTO POSITIONS (CODE, NAME) VALUES
('POS-01', 'Инженер'),
('POS-02', 'Техник'),
('POS-03', 'Оператор');


INSERT INTO USERS (CODE, FULL_NAME, POSITION_CODE) VALUES
('USER-01', 'Иванов Иван Иванович',     'POS-01'),
('USER-02', 'Петрова Мария Сергеевна',  'POS-02'),
('USER-03', 'Сидоров Алексей Петрович', 'POS-03');

INSERT INTO EQUIPMENT_TYPES (CODE, NAME, DESCRIPTION) VALUES
('EQ-01', 'Насос',        'Центробежный насос'),
('EQ-02', 'Двигатель',    'Электродвигатель'),
('EQ-03', 'Компрессор',   'Винтовой компрессор');

INSERT INTO PARAMETERS (CODE, NAME, VALUE, UNIT, EQUIPMENT_TYPE_CODE) VALUES
('PAR-01', 'Мощность',       '15',    'кВт',  'EQ-02'),
('PAR-02', 'Производительность','120','м3/ч', 'EQ-01'),
('PAR-03', 'Давление',       '8',     'бар',  'EQ-03'),
('PAR-04', 'Напряжение',     '380',   'В',    'EQ-02');

INSERT INTO PACKS (CODE, NAME, CREATED_DATE, USER_CODE, PARAMETER_CODE) VALUES
('PACK-01', 'Пачка заявок 1', '2026-09-15', 'USER-01', 'PAR-01'),
('PACK-02', 'Пачка заявок 2', '2026-09-17', 'USER-02', 'PAR-02'),
('PACK-03', 'Пачка заявок 3', '2026-09-20', 'USER-03', 'PAR-04');